In [69]:
#1-первая задача
import numpy as np
L = np.random.random((10,3))
print(L)
for i in range(L.shape[0]):
    print(L[i,np.argmin(np.absolute(L[i]-0.5))])

[[0.63695285 0.65426241 0.57982633]
 [0.08764177 0.56054516 0.16437923]
 [0.46294573 0.24862858 0.55164928]
 [0.38926806 0.73906178 0.30214766]
 [0.27244172 0.35221697 0.79328061]
 [0.008844   0.65110151 0.93845339]
 [0.54927451 0.18305313 0.23755896]
 [0.01914995 0.25695318 0.27716812]
 [0.27988193 0.48475742 0.10812806]
 [0.66260349 0.96434716 0.86336282]]
0.5798263253341532
0.5605451637006925
0.4629457328189748
0.3892680647129151
0.3522169680326308
0.6511015062102502
0.5492745124617152
0.2771681239588851
0.48475741901354463
0.6626034897591725


In [68]:
#2-ая задача
L = np.random.random((6,6))
print(L)
for i in range(L.shape[0]):
    print(np.sum(L[i])/np.min(L[:,i]))

[[0.41789345 0.0455437  0.40320135 0.24753103 0.76719587 0.14682865]
 [0.66105771 0.35886435 0.68012122 0.86442557 0.54805472 0.97277356]
 [0.14066683 0.68420126 0.5126043  0.16409229 0.8798382  0.70853288]
 [0.64821876 0.91844651 0.04725383 0.03741604 0.26010068 0.47651566]
 [0.53314944 0.85808859 0.62917749 0.64042259 0.44188596 0.13292374]
 [0.01918892 0.70170094 0.67130091 0.21067869 0.22549644 0.47702924]]
105.69607475555918
89.70059936182373
65.39017232558598
63.82160492221557
14.348997199753592
17.34374302121866


In [67]:
#3-ья задача
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
x=[x[i] for i in range(1,x.shape[0]) if (x[i-1]==0)]
print(np.max(x))

5


In [74]:
#4-ая задача
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in range(x.shape[0]):
    c=0
    for k in range(i.shape[0]): 
        if (i[k]==j): c+=1
    x[j]+=c
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]
